### ISSUE TITLE
No function clause matching in Linker

### ISSUE THREAD

**Issue by norpan** [uberbrodt/commanded_horde_registry#3]
I get the following every 60 seconds

** (FunctionClauseError) no function clause matching in Commanded.Registration.HordeRegistry.Linker.handle_info/2
(commanded_horde_registry) lib/commanded/registration/horde_registry/linker.ex:36: Commanded.Registration.HordeRegistry.Linker.handle_info(:sync_interval, %{horde_name: Commanded.Registration.HordeRegistry, sync_interval: 60000})

**Comment by norpan** [comment]
I guess it should be `:heartbeat` here:
https://github.com/uberbrodt/commanded_horde_registry/blob/7dd6462269b69bf0a6722589156adbe8b594ab55/lib/commanded/registration/horde_registry/linker.ex#L26

**Comment by uberbrodt** [comment]
fixed
